name: Greeting on variable day

on:
  push

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$REACT_APP_NEW_SECRET"
        env:
          First_Name: Mona
          REACT_APP_NEW_SECRET: ${{ secrets.REACT_APP_NEW_SECRET }}

          # 