# - name: Deploy with gh-pages
#   run: |
#     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/sneham-boop/werun.git
#     npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
#    env:
#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     REACT_APP_NEW_SECRET: ${{secrets.REACT_APP_NEW_SECRET}}

# env: 
#   GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#   REACT_APP_NEW_SECRET: "${{secrets.REACT_APP_NEW_SECRET}}"
# name: Build
# on: [push] # defaults to master
# run: |
#     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
#     npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"

name: Build and Deploy
on: [push] # defaults to master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: Build
       run: |
         git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
         npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_NEW_SECRET: "${{secrets.REACT_APP_NEW_SECRET}}"
# on: [push]
# job1: 
#   runs-on: ubuntu-latest
#   steps: 
#     - 
#       env: 
#         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#         REACT_APP_NEW_SECRET: "${{secrets.REACT_APP_NEW_SECRET}}"
#       name: Build
#       run: |
#           git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
#           npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
# jobs: ~
# name: "Build and Deploy"
# # true: 
# #   - push